C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.0.2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapsla_airmas (sla_airmasf2pywrap, zd)
      external sla_airmas
      double precision zd
      double precision sla_airmasf2pywrap
      double precision  sla_airmas
      sla_airmasf2pywrap = sla_airmas(zd)
      end


      subroutine f2pywrapsla_bear (sla_bearf2pywrap, a1, b1, a2, b
     &2)
      external sla_bear
      real a1
      real b1
      real a2
      real b2
      real sla_bearf2pywrap
      real  sla_bear
      sla_bearf2pywrap = sla_bear(a1, b1, a2, b2)
      end


      subroutine f2pywrapsla_dat (sla_datf2pywrap, utc)
      external sla_dat
      double precision utc
      double precision sla_datf2pywrap
      double precision  sla_dat
      sla_datf2pywrap = sla_dat(utc)
      end


      subroutine f2pywrapsla_dbear (sla_dbearf2pywrap, a1, b1, a2,
     & b2)
      external sla_dbear
      double precision a1
      double precision b1
      double precision a2
      double precision b2
      double precision sla_dbearf2pywrap
      double precision  sla_dbear
      sla_dbearf2pywrap = sla_dbear(a1, b1, a2, b2)
      end


      subroutine f2pywrapsla_dpav (sla_dpavf2pywrap, v1, v2)
      external sla_dpav
      double precision v1(3)
      double precision v2(3)
      double precision sla_dpavf2pywrap
      double precision  sla_dpav
      sla_dpavf2pywrap = sla_dpav(v1, v2)
      end


      subroutine f2pywrapsla_drange (sla_drangef2pywrap, angle)
      external sla_drange
      double precision angle
      double precision sla_drangef2pywrap
      double precision  sla_drange
      sla_drangef2pywrap = sla_drange(angle)
      end


      subroutine f2pywrapsla_dranrm (sla_dranrmf2pywrap, angle)
      external sla_dranrm
      double precision angle
      double precision sla_dranrmf2pywrap
      double precision  sla_dranrm
      sla_dranrmf2pywrap = sla_dranrm(angle)
      end


      subroutine f2pywrapsla_dsep (sla_dsepf2pywrap, a1, b1, a2, b
     &2)
      external sla_dsep
      double precision a1
      double precision b1
      double precision a2
      double precision b2
      double precision sla_dsepf2pywrap
      double precision  sla_dsep
      sla_dsepf2pywrap = sla_dsep(a1, b1, a2, b2)
      end


      subroutine f2pywrapsla_dsepv (sla_dsepvf2pywrap, v1, v2)
      external sla_dsepv
      double precision v1(3)
      double precision v2(3)
      double precision sla_dsepvf2pywrap
      double precision  sla_dsepv
      sla_dsepvf2pywrap = sla_dsepv(v1, v2)
      end


      subroutine f2pywrapsla_dt (sla_dtf2pywrap, epoch)
      external sla_dt
      double precision epoch
      double precision sla_dtf2pywrap
      double precision  sla_dt
      sla_dtf2pywrap = sla_dt(epoch)
      end


      subroutine f2pywrapsla_dtt (sla_dttf2pywrap, utc)
      external sla_dtt
      double precision utc
      double precision sla_dttf2pywrap
      double precision  sla_dtt
      sla_dttf2pywrap = sla_dtt(utc)
      end


      subroutine f2pywrapsla_dvdv (sla_dvdvf2pywrap, va, vb)
      external sla_dvdv
      double precision va(3)
      double precision vb(3)
      double precision sla_dvdvf2pywrap
      double precision  sla_dvdv
      sla_dvdvf2pywrap = sla_dvdv(va, vb)
      end


      subroutine f2pywrapsla_epb2d (sla_epb2df2pywrap, epb)
      external sla_epb2d
      double precision epb
      double precision sla_epb2df2pywrap
      double precision  sla_epb2d
      sla_epb2df2pywrap = sla_epb2d(epb)
      end


      subroutine f2pywrapsla_epb (sla_epbf2pywrap, date)
      external sla_epb
      double precision date
      double precision sla_epbf2pywrap
      double precision  sla_epb
      sla_epbf2pywrap = sla_epb(date)
      end


      subroutine f2pywrapsla_epco (sla_epcof2pywrap, k0, k, e)
      external sla_epco
      double precision e
      character*(*) k0
      character*(*) k
      double precision sla_epcof2pywrap
      double precision  sla_epco
      sla_epcof2pywrap = sla_epco(k0, k, e)
      end


      subroutine f2pywrapsla_epj2d (sla_epj2df2pywrap, epj)
      external sla_epj2d
      double precision epj
      double precision sla_epj2df2pywrap
      double precision  sla_epj2d
      sla_epj2df2pywrap = sla_epj2d(epj)
      end


      subroutine f2pywrapsla_epj (sla_epjf2pywrap, date)
      external sla_epj
      double precision date
      double precision sla_epjf2pywrap
      double precision  sla_epj
      sla_epjf2pywrap = sla_epj(date)
      end


      subroutine f2pywrapsla_eqeqx (sla_eqeqxf2pywrap, date)
      external sla_eqeqx
      double precision date
      double precision sla_eqeqxf2pywrap
      double precision  sla_eqeqx
      sla_eqeqxf2pywrap = sla_eqeqx(date)
      end


      subroutine f2pywrapsla_gmsta (sla_gmstaf2pywrap, date, ut)
      external sla_gmsta
      double precision date
      double precision ut
      double precision sla_gmstaf2pywrap
      double precision  sla_gmsta
      sla_gmstaf2pywrap = sla_gmsta(date, ut)
      end


      subroutine f2pywrapsla_gmst (sla_gmstf2pywrap, ut1)
      external sla_gmst
      double precision ut1
      double precision sla_gmstf2pywrap
      double precision  sla_gmst
      sla_gmstf2pywrap = sla_gmst(ut1)
      end


      subroutine f2pywrapsla_pa (sla_paf2pywrap, ha, dec, phi)
      external sla_pa
      double precision ha
      double precision dec
      double precision phi
      double precision sla_paf2pywrap
      double precision  sla_pa
      sla_paf2pywrap = sla_pa(ha, dec, phi)
      end


      subroutine f2pywrapsla_pav (sla_pavf2pywrap, v1, v2)
      external sla_pav
      real v1(3)
      real v2(3)
      real sla_pavf2pywrap
      real  sla_pav
      sla_pavf2pywrap = sla_pav(v1, v2)
      end


      subroutine f2pywrapsla_range (sla_rangef2pywrap, angle)
      external sla_range
      real angle
      real sla_rangef2pywrap
      real  sla_range
      sla_rangef2pywrap = sla_range(angle)
      end


      subroutine f2pywrapsla_ranorm (sla_ranormf2pywrap, angle)
      external sla_ranorm
      real angle
      real sla_ranormf2pywrap
      real  sla_ranorm
      sla_ranormf2pywrap = sla_ranorm(angle)
      end


      subroutine f2pywrapsla_rcc (sla_rccf2pywrap, tdb, ut1, wl, u
     &, v)
      external sla_rcc
      double precision tdb
      double precision ut1
      double precision wl
      double precision u
      double precision v
      double precision sla_rccf2pywrap
      double precision  sla_rcc
      sla_rccf2pywrap = sla_rcc(tdb, ut1, wl, u, v)
      end


      subroutine f2pywrapsla_rverot (sla_rverotf2pywrap, phi, ra, 
     &da, st)
      external sla_rverot
      real phi
      real ra
      real da
      real st
      real sla_rverotf2pywrap
      real  sla_rverot
      sla_rverotf2pywrap = sla_rverot(phi, ra, da, st)
      end


      subroutine f2pywrapsla_rvgalc (sla_rvgalcf2pywrap, r2000, d2
     &000)
      external sla_rvgalc
      real r2000
      real d2000
      real sla_rvgalcf2pywrap
      real  sla_rvgalc
      sla_rvgalcf2pywrap = sla_rvgalc(r2000, d2000)
      end


      subroutine f2pywrapsla_rvlg (sla_rvlgf2pywrap, r2000, d2000)
      external sla_rvlg
      real r2000
      real d2000
      real sla_rvlgf2pywrap
      real  sla_rvlg
      sla_rvlgf2pywrap = sla_rvlg(r2000, d2000)
      end


      subroutine f2pywrapsla_rvlsrd (sla_rvlsrdf2pywrap, r2000, d2
     &000)
      external sla_rvlsrd
      real r2000
      real d2000
      real sla_rvlsrdf2pywrap
      real  sla_rvlsrd
      sla_rvlsrdf2pywrap = sla_rvlsrd(r2000, d2000)
      end


      subroutine f2pywrapsla_rvlsrk (sla_rvlsrkf2pywrap, r2000, d2
     &000)
      external sla_rvlsrk
      real r2000
      real d2000
      real sla_rvlsrkf2pywrap
      real  sla_rvlsrk
      sla_rvlsrkf2pywrap = sla_rvlsrk(r2000, d2000)
      end


      subroutine f2pywrapsla_sep (sla_sepf2pywrap, a1, b1, a2, b2)
      external sla_sep
      real a1
      real b1
      real a2
      real b2
      real sla_sepf2pywrap
      real  sla_sep
      sla_sepf2pywrap = sla_sep(a1, b1, a2, b2)
      end


      subroutine f2pywrapsla_sepv (sla_sepvf2pywrap, v1, v2)
      external sla_sepv
      real v1(3)
      real v2(3)
      real sla_sepvf2pywrap
      real  sla_sepv
      sla_sepvf2pywrap = sla_sepv(v1, v2)
      end


      subroutine f2pywrapsla_vdv (sla_vdvf2pywrap, va, vb)
      external sla_vdv
      real va(3)
      real vb(3)
      real sla_vdvf2pywrap
      real  sla_vdv
      sla_vdvf2pywrap = sla_vdv(va, vb)
      end


      subroutine f2pywrapsla_veri (sla_verif2pywrap)
      external sla_veri
      integer sla_verif2pywrap
      integer  sla_veri
      sla_verif2pywrap = sla_veri()
      end


      subroutine f2pywrapsla_zd (sla_zdf2pywrap, ha, dec, phi)
      external sla_zd
      double precision ha
      double precision dec
      double precision phi
      double precision sla_zdf2pywrap
      double precision  sla_zd
      sla_zdf2pywrap = sla_zd(ha, dec, phi)
      end

